---
title: "Shiny Application and Reproducible Pitch"
author: "Mohammad Sulaiman"
date: "12/20/2020"
output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Developing Data Product Coursera Project

### Introduction and Overview

This presentation and the associated Shiny Application conclude the Coursera course Developing Data products project.

This peer assessed assignment has two parts. create a Shiny application and deploy it on Rstudio's servers. Second, Slidify or Rstudio Presenter to prepare a reproducible pitch presentation about your application.

### Links and Appendix

* Shiny app: https://sulaiman.shinyapps.io/RSProject/
* Source Code: https://github.com/sulaimandk/Shiny
* Presentation is available via RPubs: 

---

## mtcars dataset

### Motor Trend Car Road Tests
The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973–74 models).

### Source
Henderson and Velleman (1981), Building multiple regression models interactively. Biometrics, 37, 391–411.

```r
library(datasets)
head(mtcars, 3)
```
---

## mtcars dataset Format

A data frame with 32 observations on 11 variables.

| Index | Field | Detail |
------- | ----- | ------ |
| [, 1] | mpg | Miles/(US) gallon |
| [, 2]  | cyl | Number of cylinders |
| [, 3]	| disp | Displacement (cu.in.) |
| [, 4]	| hp | Gross horsepower |
| [, 5]	| drat | Rear axle ratio |
| [, 6]	| wt | Weight (lb/1000) |
| [, 7]	| qsec | 1/4 mile time |
| [, 8]	| vs | V/S |
| [, 9]	| am | Transmission (0 = automatic, 1 = manual) |
| [,10]	| gear | Number of forward gears |
| [,11]	| carb | Number of carburetors |

---

## Analysis code

```r
  formulaTextPoint <- reactive({
    paste("mpg ~", "as.integer(", input$variable, ")")  })
  
  fit <- reactive({
    lm(as.formula(formulaTextPoint()), data=mpgData)  })
  ...
  output$fit <- renderPrint({
    summary(fit()) })
  
  output$mpgPlot <- renderPlot({
    with(mpgData, {
      plot(as.formula(formulaTextPoint()))
      abline(fit(), col=2)
    })  })

```

